replicaCount: 1
envVars:
  - name: SPRING_PROFILES_ACTIVE
    value: "k8s"
  - name: DB_URL
    value: "jdbc:postgresql://postgresql:5432/charlesmoove"
  - name: DB_USERNAME
    value: "postgres"
  - name: DB_PASSWORD
    value: "firstpassword"
  - name: KEYCLOCK_REALM
    value: "darwin"
  - name: KEYCLOAK_SERVER_URL
    value: "http://keycloak-http/auth"
  - name: KEYCLOAK_CLIENT_ID
    value: "realm-darwin"
  - name: KEYCLOAK_CLIENT_SECRET
    value: "7ab3efee-20a1-4539-b595-65e06dd132c3"
  - name: ORIGIN_HOSTS
    value: "http://localhost:3000,http://localhost:3001,http://localhost:8081,http://localhost:8080,https://charles.continuousplatform.com"

secretEnvVars:
  - name: ENCRYPTION_KEY
    secretName: "application-aes256-key"
    secretKey: "encryption-key"

appname: darwin-application
    
image:
  repository: darwin-application
  tag: realwavelab.azurecr.io/darwin-application:darwin-v-0-1-0-rc-1
  blueTag: latest
service:
  name: darwin-application
  type: ClusterIP
  ports:
   - name: http
     port: 8080
configmaps:
  enabled: false
startcommand: 
  enabled: false
  value: "[\"/bin/sh\",\"-c\",\"/usr/sbin/nginx -c /data/darwin-ui-nginx.conf\"]"
ingress:
  enabled: false
  annotations: 
     kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - name: zup.lab.realwave.zup.me
      port: http
  tls: 
    - secretName: lab-realwave-zupme
      hosts:
        - zup.lab.realwave.zup.me
resources:
   limits:
    cpu: 1
    memory: 1536Mi
   requests:
    cpu: 128m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
imageCredentials:
  registry: realwavelab.azurecr.io
  username: realwavelab
  password: ***REMOVED***
livenessProbe:
  enabled: true
  failureThreshold: 3
  httpGet:
    path: /actuator/health
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 120
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /actuator/health
    port: 8080
    scheme: HTTP  
  initialDelaySeconds: 120
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 1   

consulnode:
  enabled: false
  repository: realwave-node-consul
  path: /opt/darwin-ui/config

istio:
  enabled: true

vault:
  enabled: false

initContainers:
  enabled: true